### ISSUE TITLE
fandduck its lower than the nozzle

### ISSUE THREAD

**Issue by DavaD85** [pkucmus/EVA#10] opened 2020-05-07 20:51 UTC
I tried to print the fanduck and it's lower than the nozzle, maybe it's the abs retraction during the print of this part, it's possible to move up a little?
Thanks

**Comment by DavaD85** [comment] 2020-05-07 20:54
![20200507_222909](https://user-images.githubusercontent.com/24620134/81343631-9f0b0000-90b5-11ea-92aa-031737140371.jpg)

**Comment by pkucmus** [comment] 2020-05-07 20:57
I'm going to pause on this one to make sure it's not a printout issue.

**Comment by pkucmus** [comment] 2020-05-27 07:42
Do I recall correctly that we talked about it on Messenger and the issue is resolved?

**Comment by PeterDavidsson** [comment] 2020-05-28 13:11
Hi,
I do also have this problem, how did you solve this?
I have tride both versions of your horn_duct.

**Comment by pkucmus** [comment] 2020-05-28 14:07
I suppose this might be an issue with different sizes of heat blocks - there seems to be two. I guess I'll need to make one that's 2mm(?) raised.

**Comment by PeterDavidsson** [comment] 2020-05-29 11:03
That would be nice.
I also hade to remove the bottomplate distance were you mount the shroud to make airflow spot on.
But 2mm higher would be very nice.

**Comment by pkucmus** [comment] 2020-05-29 19:31
Please tell me what exactly do you mean by "remove the bottomplate distance" ?

**Comment by pkucmus** [comment] 2020-05-29 20:49
I uploaded raised versions to a test branch: https://github.com/pkucmus/EVA/tree/raised_duct/stl (look for `_raised` files - it's raised 1mm (2mm seemed too much). 

Please let me know if it's better so I can release it officially.

**Comment by PeterDavidsson** [comment] 2020-06-02 12:19
now the flow is spot on for me
![after](https://user-images.githubusercontent.com/66072163/83519315-0c0a8d80-a4dc-11ea-8ddb-79fd73fa7ef4.JPG)
![before](https://user-images.githubusercontent.com/66072163/83519318-0ca32400-a4dc-11ea-90a2-772cc48d9311.JPG)

**Comment by pkucmus** [comment] 2020-06-06 19:17
Fixed with 1.1.0

**Closed by pkucmus** 2020-06-06 19:17 UTC
